build:
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
  only:
    - main

delivery:
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main

deploy:
  script:
    - chmod 600 $SSH_KEY
    - ssh -t -o StrictHostKeyChecking=no -i $SSH_KEY -p 41254 root@46.39.238.253 'docker kill test || true && docker rm test || true && docker pull baretskiy.ru:5050/alexvilno/coworking-backend && docker run --memory=8g --memory-swap=16g --name test -d -p 8085:8085 --restart=on-failure baretskiy.ru:5050/alexvilno/coworking-backend'
    - ssh -t -o StrictHostKeyChecking=no -i $SSH_KEY -p 41254 root@46.39.238.253 'docker image prune -a --force --filter "until=1h"'
  only:
    - main

cleanup:
  script:
    - docker image prune -a --force --filter "until=24h"
  only:
    - main